/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and warehouse availability */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which extract and game builds the data comes from */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All classes with their specs and number of skills */
        get: operations["listClasses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{class_slug}/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skills of a class, optionally filtered by spec */
        get: operations["listClassSkills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{class_slug}/skills/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skill detail with its damage clauses */
        get: operations["getSkill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/damage/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Expected HP loss of one cast of a skill on one target (BR-DMG-*) */
        post: operations["estimateDamage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data-quality summary of the current extract */
        get: operations["getDataQuality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-quality/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data-quality issues, paginated */
        get: operations["listDataQualityIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem details */
        Problem: {
            /** @example https://bdo-pvp-lab.local/problems/skill-not-found */
            type: string;
            /** @example Skill not found */
            title: string;
            /** @example 404 */
            status: number;
            /** @example No skill 9999 for class mystic */
            detail?: string;
            /** @example /api/v1/classes/mystic/skills/9999 */
            instance?: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            /** @enum {string} */
            warehouse: "available" | "unavailable";
        };
        ExtractInfo: {
            /** @example 2026-09-30 */
            extract_id: string;
            /**
             * @example [
             *       "20260806_094229_44630388",
             *       "20260809_234536_44631144"
             *     ]
             */
            game_builds: string[];
            /** @example 32 */
            class_count: number;
            /** @example 3272 */
            skill_count: number;
            /** Format: date-time */
            built_at: string;
        };
        ClassSummary: {
            /** @example mystic */
            class_slug: string;
            /** @example Mystic */
            class_name: string;
            /**
             * @example [
             *       "Succession",
             *       "Awakening"
             *     ]
             */
            specs: string[];
            /** @example 95 */
            skill_count: number;
        };
        SkillSummary: {
            /** @example mystic */
            class_slug: string;
            /** @example 2786 */
            skill_id: number;
            /** @example Wave Orb III */
            skill_name: string;
            /**
             * @example [
             *       "Awakening"
             *     ]
             */
            specs: string[];
            /** @example 10000 */
            cooldown_ms?: number | null;
            /** @example 1 */
            crit_rate?: number | null;
            /** @example true */
            can_down_attack: boolean;
            /** @example false */
            can_air_attack: boolean;
            /** @example 10 */
            max_targets?: number | null;
            /**
             * @description CC types this skill applies in PvP (PvE-only ones excluded, BR-CC-08)
             * @example []
             */
            pvp_cc: string[];
            /** @example 2 */
            clause_count: number;
            /**
             * @description Sum of damage_multiplier × hits over clauses (PvE)
             * @example 340.74
             */
            total_damage_multiplier?: number | null;
            /**
             * @description Sum of damage_multiplier × hits × pvp_kept_ratio over clauses with a PvP reduction
             * @example 78.76
             */
            pvp_damage_multiplier?: number | null;
            dq_status: components["schemas"]["DqStatus"];
        };
        SkillDetail: components["schemas"]["SkillSummary"] & {
            /**
             * @example [
             *       "bound"
             *     ]
             */
            pve_only_cc: string[];
            clauses: components["schemas"]["DamageClause"][];
        };
        DamageClause: {
            /** @example 1 */
            clause_index: number;
            /** @example Base damage */
            clause_label: string;
            /** @example DAM_ATT_2 */
            macro: string;
            /**
             * @description Raw percent / 100 (9698% → 96.98)
             * @example 96.98
             */
            damage_multiplier: number;
            /** @example 2 */
            hits: number;
            /** @example 0.2137 */
            pvp_kept_ratio?: number | null;
            /** @example 41.45 */
            pvp_damage_multiplier?: number | null;
            /** @example 1 */
            crit_rate?: number | null;
            /** @example null */
            dq_flag?: string | null;
        };
        /** @enum {string} */
        DqStatus: "ok" | "warning" | "no_damage";
        /** @enum {string} */
        Severity: "error" | "warning" | "info";
        AttackerStats: {
            /** @description Effective PvP AP used by this skill (BR-DMG-02 simplified: the user enters it) */
            ap: number;
            accuracy: number;
            /**
             * @description 0.2 = +20%
             * @default 0
             */
            crit_damage_bonus: number;
            /** @default 0 */
            back_attack_bonus: number;
            /** @default 0 */
            down_attack_bonus: number;
            /** @default 0 */
            air_attack_bonus: number;
        };
        DefenderStats: {
            /** @description Flat DR matching the attacker's AP type (BR-DMG-12) */
            dr: number;
            evasion: number;
            /**
             * @description Class SA bonus, e.g. 0.10 Maegu, 0.25 Gauntlet (BR-DMG-05)
             * @default 0
             */
            super_armor_dr_rate: number;
        };
        Situation: {
            /** @enum {string} */
            target_state: "standing" | "downed" | "airborne";
            /** @default false */
            from_behind: boolean;
            /**
             * @description Ignored unless target_state is standing (BR-DMG-11)
             * @default false
             */
            target_in_super_armor: boolean;
            /**
             * @description 1.05 when the attacker's class group has the advantage (BR-DMG-08)
             * @default 1
             */
            pvp_modifier: number;
        };
        DamageEstimateRequest: {
            class_slug: string;
            skill_id: number;
            attacker: components["schemas"]["AttackerStats"];
            defender: components["schemas"]["DefenderStats"];
            situation: components["schemas"]["Situation"];
        };
        ClauseEstimate: {
            clause_index: number;
            clause_label: string;
            /** @description false when the clause has no PvP reduction (BR-PVP-03) */
            included: boolean;
            expected_hp_loss: number;
        };
        DamageEstimate: {
            class_slug: string;
            skill_id: number;
            skill_name: string;
            /** @description BR-DMG-03 */
            hit_rate: number;
            /** @description Expected base damage per instance, BR-DMG-04 */
            base_damage: number;
            /** @description 0.30 base + SA bonus when applicable, BR-DMG-05 */
            damage_reduction_rate: number;
            /** @enum {string} */
            special_attack: "none" | "back" | "down" | "air";
            /** @description BR-DMG-07 */
            special_multiplier: number;
            /** @description 1 + crit_rate × (1 + crit_damage_bonus), BR-DMG-06 */
            expected_crit_multiplier: number;
            pvp_modifier: number;
            clauses: components["schemas"]["ClauseEstimate"][];
            total_expected_hp_loss: number;
            /**
             * @example [
             *       "Back attack capability is not verified in the data (BR-SPEC-01)"
             *     ]
             */
            warnings: string[];
        };
        DataQualityMetric: {
            /** @example clauses_without_pvp_reduction */
            metric: string;
            /** @example Damage clauses without PvP reduction */
            label: string;
            /** @example 133 */
            value: number;
        };
        RuleCount: {
            /** @example no_pvp_reduction */
            rule: string;
            severity: components["schemas"]["Severity"];
            /** @example 133 */
            count: number;
        };
        DataQualityReport: {
            extract_id: string;
            metrics: components["schemas"]["DataQualityMetric"][];
            rules: components["schemas"]["RuleCount"][];
        };
        DataQualityIssue: {
            issue_id: string;
            rule: string;
            severity: components["schemas"]["Severity"];
            class_slug?: string | null;
            skill_id?: number | null;
            detail: string;
        };
        DataQualityIssuePage: {
            items: components["schemas"]["DataQualityIssue"][];
            total: number;
            limit: number;
            offset: number;
        };
    };
    responses: {
        /** @description Class or skill not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Invalid request body or a skill that cannot be estimated */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @example mystic */
        ClassSlug: string;
        /** @example 2786 */
        SkillId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Extract information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractInfo"];
                };
            };
        };
    };
    listClasses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Classes sorted by class_name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSummary"][];
                };
            };
        };
    };
    listClassSkills: {
        parameters: {
            query?: {
                /** @description Catalog build label (e.g. "Awakening", "Succession", "Single build"). */
                spec?: string;
            };
            header?: never;
            path: {
                /** @example mystic */
                class_slug: components["parameters"]["ClassSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skills sorted by pvp_damage_multiplier descending (nulls last), then skill_name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillSummary"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example mystic */
                class_slug: components["parameters"]["ClassSlug"];
                /** @example 2786 */
                skill_id: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skill detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    estimateDamage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "class_slug": "mystic",
                 *       "skill_id": 2786,
                 *       "attacker": {
                 *         "ap": 1085,
                 *         "accuracy": 1353,
                 *         "crit_damage_bonus": 0.2,
                 *         "back_attack_bonus": 0,
                 *         "down_attack_bonus": 0,
                 *         "air_attack_bonus": 0
                 *       },
                 *       "defender": {
                 *         "dr": 740,
                 *         "evasion": 1197,
                 *         "super_armor_dr_rate": 0.1
                 *       },
                 *       "situation": {
                 *         "target_state": "downed",
                 *         "from_behind": false,
                 *         "target_in_super_armor": false,
                 *         "pvp_modifier": 1
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["DamageEstimateRequest"];
            };
        };
        responses: {
            /** @description Estimate with full breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DamageEstimate"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getDataQuality: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics and issue counts per rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityReport"];
                };
            };
        };
    };
    listDataQualityIssues: {
        parameters: {
            query?: {
                rule?: string;
                severity?: components["schemas"]["Severity"];
                class_slug?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of issues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityIssuePage"];
                };
            };
        };
    };
}
